window.func_Gs=function(lib,game,ui,get,ai,_status){
window.版本_version='1.84.6.4';
window.forced=true;
window.file_Gs={
"game2.js":"game/game.js",
"extension2.js":"extension/MCBE命令助手包/extension.js",
"identity2.js":"mode/identity.js",
};
window.file_Mt_Gs={
"loseHp.mp3":'audio/effect/loseHp.mp3',
"recover.mp3":'audio/effect/recover.mp3',
"damage.mp3":'audio/effect/damage.mp3',
"damage2.mp3":'audio/effect/damage2.mp3',
"damage_fire.mp3":'audio/effect/damage_fire.mp3',
"damage_fire2.mp3":'audio/effect/damage_fire2.mp3',
"damage_thunder.mp3":'audio/effect/damage_thunder.mp3',
"damage_thunder2.mp3":'audio/effect/damage_thunder2.mp3',
"mc_boss_zhaogao.jpg":'image/character/mc_boss_zhaogao.jpg',
"mc_boss_molingzi.jpg":'image/character/mc_boss_molingzi.jpg',
"mc_boss_mengtian.jpg":'image/character/mc_boss_mengtian.jpg',
"mc_boss_404.jpg":'image/character/mc_boss_404.jpg',
"mc_boss_chi.jpg":'image/character/mc_boss_chi.jpg',
"mc_boss_mei.jpg":'image/character/mc_boss_mei.jpg',
"mc_boss_wang.jpg":'image/character/mc_boss_wang.jpg',
"mc_boss_liang.jpg":'image/character/mc_boss_liang.jpg',
"mc_boss_niutou.jpg":'image/character/mc_boss_niutou.jpg',
"mc_boss_mamian.jpg":'image/character/mc_boss_mamian.jpg',
"mc_boss_luocha.jpg":'image/character/mc_boss_luocha.jpg',
"mc_boss_yecha.jpg":'image/character/mc_boss_yecha.jpg',
"mc_boss_zhuge.png":'image/card/mc_boss_zhuge.png',
"mc_boss_guibao.jpg":'image/character/mc_boss_guibao.jpg',
"mc_boss_yanwang1.mp3":"audio/skill/mc_boss_yanwang1.mp3",
"xinfu_tushe2.mp3":"audio/skill/xinfu_tushe2.mp3",
"noname.jpg":"extension/MCBE命令助手包/noname.jpg",
"xinlianyue.jpg":"extension/MCBE命令助手包/xinlianyue.jpg",
"bakabaka.jpg":"extension/MCBE命令助手包/bakabaka.jpg",
};
game.print(window.版本_version);
window.func_Gsed=true;
if(window.版本_version!=lib.config.联机包_version){
if(!window.forced){
if(confirm(!_status.Gs_gx&&"扩展(联机包)有更新是否更新？")&&!_status.Gs_gx){
game.gx(null,null,true);
return;
};
}else{
if(!_status.Gs_gx){
game.gx(null,null,true);
return;
};
};
};
if(!lib.mc_boss_gui){
game.gx(null,null,true);
};
game.gxsc();
}
